float64[] start_xyz
float64[] start_quat_wxyz
float64[] goal_xyz
float64[] goal_quat_wxyz
string planner_name
float64 time_limit
float64 safety_margin
float64 robot_collision_radius
float64[] env_bounds
---
bool success
string message
---
string stage
